version: "3.8"

services:
  saltmarsh:
    container_name: saltmarsh
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - mysql

  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'saltmarsh'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - mysql

networks:
  mysql:
    name: mysql

volumes:
  db:
    driver: local
