version: "3.8"

services:
  saltmarsh:
    container_name: saltmarsh
    build: .
    env_file:
      - env_file
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: unless-stopped
    env_file:
      - env_file
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  db:
    driver: local
