name: build and deploy

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: docker build -t Saltmarsh .

        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y