name: build and deploy

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  PROJECT_NAME: saltmarsh


concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Touch archive
        run: touch saltmarsh.tar.gz

      - name: Create tar archive
        run: tar --exclude='saltmarsh.tar.gz' -cvzf saltmarsh.tar.gz .

      - name: Upload tar archive as artifact
        uses: actions/upload-artifact@master
        with:
          name: saltmarsh.tar.gz
          path: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar.gz
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download tar archive as artifact
        uses: actions/download-artifact@master
        with:
          name: saltmarsh.tar.gz
          path: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar.gz

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: SCP Image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar.gz
          target: ~/Saltmarsh

      - name: SSH, Load & Run Dockerfile
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf Saltmarsh
            mkdir Saltmarsh
            cd Saltmarsh
            mv github/workspace/saltmarsh.tar.gz/saltmarsh.tar.gz saltmarsh.tar.gz
            rm -rf github
            tar -xvzf saltmarsh.tar.gz .
            rm saltmarsh.tar.gz
            docker compose down
            docker compose up --build --detach --force-recreate
            exit
