name: build and deploy

on:
  workflow_dispatch:

  push:
  pull_request:
    branches:
      - 'master'

env:
  PROJECT_NAME: saltmarsh


concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: docker build -t $PROJECT_NAME .

      - name: Save Dockerfile as Tar
        run: docker save -o $PROJECT_NAME.tar $PROJECT_NAME:latest

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@master
        with:
          name: saltmarsh.tar
          path: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Docker Image as Artifact
        uses: actions/download-artifact@master
        with:
          name: saltmarsh.tar
          path: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: SCP Image
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: /home/runner/work/Saltmarsh/Saltmarsh/saltmarsh.tar
          target: ~/Saltmarsh

      - name: SSH, Load & Run Dockerfile
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd Saltmarsh
            mv github/workspace/saltmarsh.tar/saltmarsh.tar saltmarsh.tar
            rm -rf github
            ls -la
            pwd
            docker kill Saltmarsh
            docker container prune --force
            docker image rm saltmarsh
            docker load --input saltmarsh.tar
            rm saltmarsh.tar
            docker run -d --name=Saltmarsh --env-file /root/Saltmarsh/env_file saltmarsh
            exit
